const COMPANIES = {
  BBC: 'BBC',
  SD9: 'SD9',
  TBC: 'TBC',
  PVS: 'PVS',
  PGC: 'PGC',
  TED: 'TED',
  PMS: 'PMS',
  PGI: 'PGI',
  NHT: 'NHT',
  GAS: 'GAS',
  VCS: 'VCS',
  SSG: 'SSG',
  ABW: 'ABW',
  AGR: 'AGR',
  APG: 'APG',
  APS: 'APS',
  BMS: 'BMS',
  BSI: 'BSI',
  BVS: 'BVS',
  CTS: 'CTS',
  EVS: 'EVS',
  FTS: 'FTS',
  ORS: 'ORS',
  SBS: 'SBS',
  SHS: 'SHS',
  VCI: 'VCI',
  VDS: 'VDS',
  VFS: 'VFS',
  VIX: 'VIX',
  VND: 'VND',
  VCB: 'VCB',
  TCB: 'TCB',
  VPB: 'VPB',
  LPB: 'LPB',
  VIB: 'VIB',
  SSB: 'SSB',
  EIB: 'EIB',
  TPB: 'TPB',
  MSB: 'MSB',
  OCB: 'OCB',
  NAB: 'NAB',
  BAB: 'BAB',
  BVB: 'BVB',
  ABB: 'ABB',
  VBB: 'VBB',
  PGB: 'PGB',
  VAB: 'VAB',
  KLB: 'KLB',
  SGB: 'SGB',
  PVI: 'PVI',
  AST: 'AST',
  DNW: 'DNW',
  MPC: 'MPC',
};

const CAFEF_API = `https://cafef.vn/du-lieu/Ajax/CongTy/BaoCaoTaiChinh.aspx?sym=`;

export { COMPANIES, CAFEF_API };